"""Reading and writing ``zeyvor.yml``.

Two things this module takes seriously.

**Typos must be caught, with a line number.** The contract is hand-edited in
pull requests. A silently ignored ``nullible: false`` is worse than a crash: the
check quietly stops enforcing the thing the reviewer believes it enforces. Every
unknown key is an error, and every error names its line and suggests the key the
author probably meant.

**The output has to be pleasant to read.** Fixed key order, inline short lists,
no line wrapping mid-sentence, and a header explaining what the file is for.
"""

from __future__ import annotations

import difflib
from typing import Any

import yaml

from .models import (
    CONTRACT_SCHEMA_VERSION,
    ColumnContract,
    Contract,
    Defaults,
    Severity,
    TableContract,
)

HEADER = """\
# Zeyvor data contract — what these columns are supposed to mean.
#
# Generated by `zeyvor init`, then edited by hand and reviewed like code.
# `zeyvor check` compares live data against this file and fails the build when
# the data stops matching. Every clause is optional; omit one to stop checking
# it, or set `ignore: true` on a column to retire it while keeping the intent
# visible in review.
"""

CONTRACT_KEYS = {"version", "generated_by", "generated_at", "defaults", "tables"}
DEFAULTS_KEYS = {"on_violation"}
TABLE_KEYS = {
    "source",
    "profile_fingerprint",
    "min_rows",
    "allow_new_columns",
    "allow_missing_columns",
    "on_violation",
    "columns",
}
COLUMN_KEYS = {
    "means",
    "type",
    "formats",
    "nullable",
    "max_null_rate",
    "unique",
    "categories",
    "categories_closed",
    "min",
    "max",
    "no_pii",
    "known_issues",
    "ignore",
    "on_violation",
}

COLUMN_KEY_ORDER = [
    "means",
    "type",
    "formats",
    "nullable",
    "max_null_rate",
    "unique",
    "categories",
    "categories_closed",
    "min",
    "max",
    "no_pii",
    "known_issues",
    "ignore",
    "on_violation",
]


class ContractError(ValueError):
    """A contract file that cannot be trusted to mean what it says."""


# ── line tracking ─────────────────────────────────────────────────────────────


def _line_index(text: str) -> dict[tuple[str, ...], int]:
    """Map each mapping-key path to its 1-based line number.

    Walking the composed node tree keeps line information out of the parsed data
    itself, so the loaded structure stays clean while errors stay precise.
    """
    index: dict[tuple[str, ...], int] = {}

    def walk(node: Any, path: tuple[str, ...]) -> None:
        if isinstance(node, yaml.MappingNode):
            for key_node, value_node in node.value:
                key = str(getattr(key_node, "value", ""))
                index[path + (key,)] = key_node.start_mark.line + 1
                walk(value_node, path + (key,))
        elif isinstance(node, yaml.SequenceNode):
            for item in node.value:
                walk(item, path)

    try:
        root = yaml.compose(text)
    except yaml.YAMLError:
        return index
    if root is not None:
        walk(root, ())
    return index


class _Validator:
    def __init__(self, lines: dict[tuple[str, ...], int]) -> None:
        self.lines = lines

    def at(self, path: tuple[str, ...]) -> str:
        line = self.lines.get(path)
        return f" (line {line})" if line else ""

    def check_keys(self, mapping: dict[str, Any], allowed: set[str], path: tuple[str, ...]) -> None:
        for key in mapping:
            if key in allowed:
                continue
            suggestion = difflib.get_close_matches(str(key), sorted(allowed), n=1, cutoff=0.6)
            hint = f" Did you mean '{suggestion[0]}'?" if suggestion else ""
            where = ".".join(path + (str(key),)) or str(key)
            raise ContractError(
                f"Unknown key '{key}' in {where}{self.at(path + (str(key),))}.{hint}"
            )

    def mapping(self, value: Any, path: tuple[str, ...], what: str) -> dict[str, Any]:
        if value is None:
            return {}
        if not isinstance(value, dict):
            raise ContractError(
                f"{what} must be a mapping, got {type(value).__name__}{self.at(path)}"
            )
        return value

    def string_list(self, value: Any, path: tuple[str, ...], what: str) -> list[str]:
        if value is None:
            return []
        if isinstance(value, (str, int, float)):
            return [str(value)]
        if not isinstance(value, list):
            raise ContractError(f"{what} must be a list{self.at(path)}")
        return [str(v) for v in value]

    def boolean(self, value: Any, path: tuple[str, ...], what: str) -> bool | None:
        if value is None:
            return None
        if not isinstance(value, bool):
            raise ContractError(f"{what} must be true or false, got {value!r}{self.at(path)}")
        return value

    def number(self, value: Any, path: tuple[str, ...], what: str) -> float | None:
        if value is None:
            return None
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise ContractError(f"{what} must be a number, got {value!r}{self.at(path)}")
        return float(value)

    def severity(self, value: Any, path: tuple[str, ...]) -> Severity | None:
        if value is None:
            return None
        try:
            return Severity(str(value).lower())
        except ValueError:
            valid = ", ".join(s.value for s in Severity)
            raise ContractError(
                f"on_violation must be one of: {valid} — got {value!r}{self.at(path)}"
            ) from None


# ── loading ───────────────────────────────────────────────────────────────────


def loads(text: str) -> Contract:
    try:
        raw = yaml.safe_load(text)
    except yaml.YAMLError as exc:
        mark = getattr(exc, "problem_mark", None)
        where = f" at line {mark.line + 1}, column {mark.column + 1}" if mark else ""
        problem = getattr(exc, "problem", str(exc))
        raise ContractError(f"Could not parse the contract{where}: {problem}") from None

    if raw is None:
        raise ContractError("The contract file is empty.")
    if not isinstance(raw, dict):
        raise ContractError("The contract must be a mapping at the top level.")

    v = _Validator(_line_index(text))
    v.check_keys(raw, CONTRACT_KEYS, ())

    version = raw.get("version", CONTRACT_SCHEMA_VERSION)
    if not isinstance(version, int) or version < 1:
        raise ContractError(f"version must be a positive integer, got {version!r}")
    if version > CONTRACT_SCHEMA_VERSION:
        raise ContractError(
            f"This contract declares version {version}, but this Zeyvor "
            f"understands up to {CONTRACT_SCHEMA_VERSION}. Upgrade Zeyvor."
        )

    defaults_raw = v.mapping(raw.get("defaults"), ("defaults",), "defaults")
    v.check_keys(defaults_raw, DEFAULTS_KEYS, ("defaults",))
    defaults = Defaults(
        on_violation=v.severity(defaults_raw.get("on_violation"), ("defaults", "on_violation"))
        or Severity.FAIL
    )

    tables_raw = v.mapping(raw.get("tables"), ("tables",), "tables")
    if not tables_raw:
        raise ContractError("The contract declares no tables.")

    tables: dict[str, TableContract] = {}
    for table_name, table_body in tables_raw.items():
        path = ("tables", str(table_name))
        body = v.mapping(table_body, path, f"table '{table_name}'")
        v.check_keys(body, TABLE_KEYS, path)

        columns_raw = v.mapping(body.get("columns"), path + ("columns",), "columns")
        columns: dict[str, ColumnContract] = {}
        for column_name, column_body in columns_raw.items():
            cpath = path + ("columns", str(column_name))
            cbody = v.mapping(column_body, cpath, f"column '{column_name}'")
            v.check_keys(cbody, COLUMN_KEYS, cpath)

            categories = cbody.get("categories")
            columns[str(column_name)] = ColumnContract(
                name=str(column_name),
                means=str(cbody["means"]) if cbody.get("means") is not None else None,
                type=str(cbody["type"]) if cbody.get("type") is not None else None,
                formats=v.string_list(cbody.get("formats"), cpath + ("formats",), "formats"),
                nullable=v.boolean(cbody.get("nullable"), cpath + ("nullable",), "nullable"),
                max_null_rate=v.number(
                    cbody.get("max_null_rate"), cpath + ("max_null_rate",), "max_null_rate"
                ),
                unique=v.boolean(cbody.get("unique"), cpath + ("unique",), "unique"),
                categories=(
                    v.string_list(categories, cpath + ("categories",), "categories")
                    if categories is not None
                    else None
                ),
                categories_closed=bool(cbody.get("categories_closed", False)),
                minimum=cbody.get("min"),
                maximum=cbody.get("max"),
                no_pii=bool(cbody.get("no_pii", False)),
                known_issues=v.string_list(
                    cbody.get("known_issues"), cpath + ("known_issues",), "known_issues"
                ),
                ignore=bool(cbody.get("ignore", False)),
                on_violation=v.severity(cbody.get("on_violation"), cpath + ("on_violation",)),
            )

        min_rows = body.get("min_rows")
        if min_rows is not None and (isinstance(min_rows, bool) or not isinstance(min_rows, int)):
            raise ContractError(
                f"min_rows must be an integer, got {min_rows!r}{v.at(path + ('min_rows',))}"
            )

        tables[str(table_name)] = TableContract(
            name=str(table_name),
            source=str(body.get("source", "") or ""),
            profile_fingerprint=str(body.get("profile_fingerprint", "") or ""),
            min_rows=min_rows,
            allow_new_columns=bool(body.get("allow_new_columns", True)),
            allow_missing_columns=bool(body.get("allow_missing_columns", False)),
            columns=columns,
            on_violation=v.severity(body.get("on_violation"), path + ("on_violation",)),
        )

    return Contract(
        version=version,
        generated_by=str(raw.get("generated_by", "") or ""),
        generated_at=str(raw.get("generated_at", "") or ""),
        defaults=defaults,
        tables=tables,
    )


def load(path: str) -> Contract:
    try:
        with open(path, encoding="utf-8") as handle:
            text = handle.read()
    except FileNotFoundError:
        raise ContractError(f"No contract at {path}. Create one with: zeyvor init") from None
    return loads(text)


# ── dumping ───────────────────────────────────────────────────────────────────


class _Flow(list):
    """A list rendered inline, so `formats: ["####-##-##"]` stays on one line."""


class _Dumper(yaml.SafeDumper):
    def increase_indent(self, flow: bool = False, indentless: bool = False):  # noqa: D102
        # Indent block sequences under their key, which reads better in review.
        return super().increase_indent(flow, False)


_Dumper.add_representer(
    _Flow,
    lambda dumper, data: dumper.represent_sequence(
        "tag:yaml.org,2002:seq", list(data), flow_style=True
    ),
)


def _column_body(column: ColumnContract) -> dict[str, Any]:
    body: dict[str, Any] = {
        "means": column.means,
        "type": column.type,
        "formats": _Flow(column.formats) if column.formats else None,
        "nullable": column.nullable,
        "max_null_rate": column.max_null_rate,
        "unique": column.unique,
        "categories": _Flow(column.categories) if column.categories else None,
        "categories_closed": column.categories_closed or None,
        "min": column.minimum,
        "max": column.maximum,
        "no_pii": column.no_pii or None,
        "known_issues": _Flow(column.known_issues) if column.known_issues else None,
        "ignore": column.ignore or None,
        "on_violation": column.on_violation.value if column.on_violation else None,
    }
    return {key: body[key] for key in COLUMN_KEY_ORDER if body.get(key) is not None}


def dumps(contract: Contract, *, header: bool = True) -> str:
    payload: dict[str, Any] = {"version": contract.version}
    if contract.generated_by:
        payload["generated_by"] = contract.generated_by
    if contract.generated_at:
        payload["generated_at"] = contract.generated_at
    if contract.defaults.on_violation is not Severity.FAIL:
        payload["defaults"] = {"on_violation": contract.defaults.on_violation.value}

    tables: dict[str, Any] = {}
    for name, table in contract.tables.items():
        body: dict[str, Any] = {}
        if table.source:
            body["source"] = table.source
        if table.profile_fingerprint:
            body["profile_fingerprint"] = table.profile_fingerprint
        if table.min_rows is not None:
            body["min_rows"] = table.min_rows
        if not table.allow_new_columns:
            body["allow_new_columns"] = False
        if table.allow_missing_columns:
            body["allow_missing_columns"] = True
        if table.on_violation:
            body["on_violation"] = table.on_violation.value
        body["columns"] = {
            column_name: _column_body(column) for column_name, column in table.columns.items()
        }
        tables[name] = body
    payload["tables"] = tables

    text = yaml.dump(
        payload,
        Dumper=_Dumper,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
        width=10_000,  # never wrap a `means` sentence mid-word
        indent=2,
    )
    return (HEADER + "\n" + text) if header else text


def dump(contract: Contract, path: str, *, header: bool = True) -> None:
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(dumps(contract, header=header))


__all__ = ["ContractError", "loads", "load", "dumps", "dump", "HEADER"]
